# This workflow will build a Java project with Brachyra
# For more information see: docs/development/brachyura.md

name: Java CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release_build:
        description: "Build as release (-Dbuild.release=true)"
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          gradle-version: current

      - name: Build with Gradle
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.release_build }}" = "true" ]; then
            ./gradlew :neoforge:build -Dbuild.release=true
          else
            ./gradlew build
          fi

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: iris-artifacts
          path: build/libs
